version: '3'
services:
  postgres:
#    image: 'postgres:10.0'
    image: 'postgres:9.6.6'
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - './init/init.sql:/docker-entrypoint-initdb.d/00database-init.sql'